#!/usr/bin/python3

import sys

def factorize(n):
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return (i, n//i)
    return None

filename = sys.argv[1]

with open(filename) as f:
    for line in f:
        n = int(line.strip())
        factors = factorize(n)
        while factors:
            print(f"{n}={factors[0]}*{factors[1]}")
            n = factors[0]
            factors = factorize(n)
